# Config file for automatic testing at travis-ci.org

sudo: required
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip

env:
  - TOX_ENV=py27-django-111
  - TOX_ENV=py34-django-111
  - TOX_ENV=py35-django-111
  - TOX_ENV=py36-django-111
  - TOX_ENV=py34-django-20
  - TOX_ENV=py35-django-20
  - TOX_ENV=py36-django-20
  - TOX_ENV=py37-django-20
  - TOX_ENV=py35-django-21
  - TOX_ENV=py36-django-21
  - TOX_ENV=py37-django-21

matrix:
  fast_finish: true

install:
  - pip install pipenv
  - pipenv install --dev --system --deploy

script:
  - tox -e $TOX_ENV

after_success:
  - codecov -e $TOX_ENV
