# Config file for automatic testing at travis-ci.org

language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip

matrix:
  fast_finish: true

install:
  - pip install pipenv
  - pipenv install --dev --system --deploy

script: tox

after_success: codecov
